### ISSUE TITLE
Operations storage variable

### ISSUE THREAD

**Issue by Bill-1991** [Bill-1991/Scheduler#2]
**Create a file variables.js and create an array of objects in it.**
**Each object wiil contain each operation's content. E.g**
**help operation will be "scheduler 1 help".**
So the content of the object for this op must be: **`{ id: "", op: "" }`**
**"scheduler" will be excluded from the input on later issue, so it doesn't need to be in the operation."**
We'll leave the content as an empty string to fill it later from the input.

All operations can be conducted from **issue 1**.
Export the variable at the end.

**Comment by AndreyDmitriev39r** [comment]
I am not sure if this will fit in slash commands flow?

**Comment by Bill-1991** [comment]
Yes, these will not be needed anymore, i'm gonna delete them

**Comment by Bill-1991** [comment]
Closing cos it won't be needed
